### ISSUE TITLE
Doxygen Header Broken

### ISSUE THREAD

**Issue by ifknot** [fingeg/DoxygenComments#16] opened 2021-11-21 00:19 UTC
Header no longer seems to be recognized and does not auto populate with 

/*****************************************************************//**
 * \file   $FILENAME
 * \brief  $BRIEF$END
 * 
 * \author $USERNAME
 * \date   $MONTHNAME_EN $YEAR
 *********************************************************************/

But, instead, just uses the default.

Microsoft Visual Studio Community 2019
Version 16.11.7
VisualStudio.16.Release/16.11.7+31911.196
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA821
Microsoft Visual C++ 2019

**Comment by kaminskyalexander** [comment] 2021-11-25 17:19
Experiencing the same issue, Visual Studio Community 2019, with the latest version of the extension. Header no longer generates and cursor is often placed at the end of the line instead of where it should be.

**Comment by kaminskyalexander** [comment] 2021-11-25 17:41
A solution for now is to revert to a previous version. This probably has something to do with the author adding support for VS2022.

I reverted to https://github.com/fingeg/DoxygenComments/tree/69bbf575e09ac7fed5cfa705ca173c74af322eff and it works as intended.

Note you'll probably have to build it yourself (I couldn't find any older releases). Make sure to disable auto update until a fix is out.

**Comment by fingeg** [comment] 2022-02-14 05:29
header fixed in #18

**Closed as completed** 2022-02-14 06:09 UTC

**Comment by fingeg** [comment] 2022-02-14 06:11
Removed a wrong cursor offset. Hopefully fixes your problem
